name: Linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node modules
        run: npm install

      - name: Build production project
        run: npm run build:prod
        if: always()

      - name: Linting typescript
        run: npm run lint:ts
        if: always()

      - name: Linting css
        run: npm run lint:scss
        if: always()

      - name: Unit testing
        run: npm run test:unit
        if: always()

      - name: Build storybook
        run: npm run storybook:build
        if: always()

      - name: Screenshot testing
        run: npm run test:ui:ci
        if: always()


